Repository neurostuff/PyMARE, pull requests merged in 2024-04, with the labels that each got.

#118 Drop support for Python 3.6 and 3.7
  .github/workflows/testing.yml
  .readthedocs.yml
  pymare/__init__.py
  pymare/datasets/__init__.py
  pymare/datasets/metadat.py
  pymare/effectsize/__init__.py
  pymare/effectsize/base.py
  pymare/effectsize/expressions.py
  pymare/estimators/__init__.py
  pymare/estimators/combination.py
  pymare/results.py
  pymare/tests/conftest.py
  pymare/tests/test_combination_tests.py
  pymare/tests/test_core.py
  pymare/tests/test_datasets.py
  pymare/tests/test_effectsize_base.py
  pymare/tests/test_effectsize_expressions.py
  pymare/tests/test_estimators.py
  pymare/tests/test_results.py
  pymare/tests/test_stan_estimators.py
  pymare/tests/test_stats.py
  pymare/tests/test_utils.py
  pymare/utils.py
  setup.cfg
Labels: enhancement

#82 Support Python 3.10
  .github/workflows/testing.yml
  docs/installation.rst
  setup.cfg
Labels: maintenance

#108 Fix StanMetaRegression estimator
  pymare/core.py
  pymare/effectsize/base.py
  pymare/effectsize/expressions.py
  pymare/estimators/estimators.py
  pymare/results.py
  pymare/tests/test_stan_estimators.py
  setup.cfg
Labels: bug

#117 Add an inflation factor to correct for multiple contrasts in Stouffer's combination test
  pymare/estimators/combination.py
  pymare/tests/test_combination_tests.py
Labels: enhancement, breaking-change

#119 Support Python 3.11
  .github/workflows/testing.yml
  docs/installation.rst
  pyproject.toml
  setup.cfg
Labels: enhancement, maintenance

#121 Support precomputed correlation matrix for calculating variance inflation term in Stouffers
  .github/workflows/testing.yml
  pymare/estimators/combination.py
  pymare/tests/test_combination_tests.py
  pymare/tests/test_results.py
Labels: enhancement
